select `ID`,`NETVALUE`,`HANDOVERED`,`DESCREPTION`,`SETTLED`,`CREATEDAT`,`HANDOVERAT`,`SETTLEAT`,`REFERANCEBILLITEM_ID` 
from billitem WHERE `CREATER_ID`=13473486 and `REFERANCEBILLITEM_ID` is not null;
